openapi: 3.0.3
info:
  title: API First
  version: 1.0.0
  description: Api First

servers:
  - url: http://localhost:3000

components:
  schemas:
    HelloResponse:
      type: object
    Products:
      type: object
      required:
        - name
        - price
        - category
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 40
        description:
          type: string
          maxLength: 200
        price:
          type: number
          minimum: 0
          multipleOf: 0.01
        category:
          type: string
          enum: [
            electronics,
            clothing,
            books,
            home_appliances
          ]
paths:
  /hello:
    get:
      summary: Hello World
      responses: 
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'

   /users:
    post:
      summary: Crear un nuevo usuario
      requestBody:
      required: true
      content:
        application/json:
        schema:
          type: object
          required:
          - name
          - age
          - email
          properties:
          name:
            type: string
            minLength: 2
          age:
            type: integer
            minimum: 18
          email:
            type: string
            format: email
      responses:
      '201':
        description: Usuario creado correctamente
        content:
        application/json:
          schema:
          type: object
          properties:
            id:
            type: string
            name:
            type: string
            age:
            type: integer
            email:
            type: string