openapi: 3.1.1
info:
  title: API First
  version: 1.0.0
  description: Api First
servers:
  - url: http://localhost:3000
paths:
  /hello:
     get:
     summary: Hello World
     responses: 
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      