openapi: 3.0.3
info:
  title: API First
  version: 1.0.0
  description: Api First
servers:
  - url: http://localhost:3000
    components:
  schemas:
    HelloResponse:
      type: object
paths:
  /hello:
    get:
      summary: Hello World
      responses: 
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'


# Creacion de nuevo usuario

/users:
  post:
    summary: Crear un nuevo usuario
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - age
              - email
            properties:
              name:
                type: string
                minLength: 2
              age:
                type: integer
                minimum: 18
              email:
                type: string
                format: email
    responses:
      '201':
        description: Usuario creado correctamente
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                age:
                  type: integer
                email:
                  type: string

/users/{id}
  get:
    summary: Obtener un usuario por id
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    responses:
      '200': 
        description: Usuario encontrado
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      '404':
        description: Usuario no encontrado
        content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
                  example: "Usuario no encontrado"          